package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/go-graphql-demo/gqlgen/graph/model"
	"github.com/go-graphql-demo/gqlgen/util"
)

// Odds is the resolver for the odds field.
func (r *queryResolver) Odds(ctx context.Context) ([]*model.Odd, error) {
	_ = util.ImportJSONFromFile("list.json", &r.odds)
	return r.odds, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
